version: '2'
services:
    jhipstermongodbsample-app:
        image: jhipstermongodbsample
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATA_MONGODB_URI=mongodb://jhipstermongodbsample-mongodb:27017
            - SPRING_DATA_MONGODB_DATABASE=jhipsterMongoDBSample
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    jhipstermongodbsample-mongodb:
        extends:
            file: mongodb.yml
            service: jhipstermongodbsample-mongodb
